### ISSUE TITLE
State - Putignano is repeated

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [hiiamrohit/Countries-States-Cities-database#25]
State - *Putignano* is repeated and the repeated value is having an extra `,`

(23500, 'Parabita', 1872),
(23501, 'Polignano a Mare', 1872),
(23502, 'Pulsano', 1872),
**(23503, 'Putignano', 1872),**
**(23504, 'Putignano,', 1872),**
(23505, 'Racale', 1872),
(23506, 'Ruffano', 1872),
(23507, 'Rutigliano', 1872),

If I remove that duplicate value, then all the indexes will become inconsistent. Should I remove it and update all other indexes and send you a PR?

**Comment by harpreetkhalsagtbit** [comment]
#16 already fixed here

**Comment by theo4u** [comment]
you can just close it
