### ISSUE TITLE
some issue and some data

### ISSUE THREAD

**Issue by Chalfouh** [hiiamrohit/Countries-States-Cities-database#44]
Ramy,Sublimity,Byram,Ontario,District of Columbia,Cokato,Lowa, Medfield and Trimble are not states in the united states
New jersey is duplicated
and here some other cities in zimbabwe
 INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Beitbridge', 4119);

INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Gwanda', 4119);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Lupane', 4118);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Hwange', 4118);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Victoria Falls', 4118);

INSERT INTO `cities`(`name`, state_id) 
	VALUES ('Banket', 4116);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Chegutu', 4116);
 
INSERT INTO `cities`(`name`, state_id) 
	VALUES ('Chinhoyi', 4116);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Kadoma', 4116);
 
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Kariba', 4116);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Karoi', 4116);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Mhangura', 4116);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Norton', 4116);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Chivhu', 4115);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Marondera', 4115);
INSERT INTO `cities`(`name`, state_id) 
	VALUES ('Murewa', 4115);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Mutoko', 4115);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Ruwa', 4115);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Bindura', 4114);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Glendale', 4114);
INSERT INTO `cities` (`name`, state_id) 
	VALUES ('Mvurwi', 4114);
INSERT INTO `cities`(`name`, state_id) 
	VALUES ('Shamva', 4114);

**Comment by javydreamercsw** [comment]
Will fix this in PR #46. Thanks!
